# Config adapted from:
# https://www.electron.build/multi-platform-build#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows
sudo: true

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js:
        - node
        - 8.10
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: node_js
      node_js:
        - node
        - 8.10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
            - xorriso

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  yarn: true
  directories:
    - node_modules
    - src/node_modules
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/docker

install:
  - export CXX="g++-4.8"
  - yarn
  # On Linux, initialize "virtual display". See before_script
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      /sbin/start-stop-daemon \
      --start \
      --quiet \
      --pidfile /tmp/custom_xvfb_99.pid \
      --make-pidfile \
      --background \
      --exec /usr/bin/Xvfb \
      -- :99 -ac -screen 0 1280x1024x16
    else
      :
    fi
before_script:
  # On Linux, create a "virtual display". This allows browsers to work properly
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

script:
  - yarn run build || travis_terminate 1
  - yarn run test-e2e -- --retries 2

after_success:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       yarn run release:linux
    else
       yarn run release:mac
    fi

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true