matrix:
  include:
  - os: linux
    language: node_js
    node_js: '9'
    sudo: required
    dist: xenial
    env:
    - PATH=/snap/bin:$PATH
    addons:
      apt:
        packages:
        - google-chrome-stable
        - snapd
        - openjpeg-tools
        - rpm
        - bsdtar
        - xvfb
        - libxtst6
        - libxss1
        - libgtk2.0-0
        - libnss3
        - libasound2
        - libgconf-2-4
  - os: osx
    language: node_js
    osx_image: xcode9.0
    node_js: '9'
    sudo: required
    env:
    - HOMEBREW_CASK_OPTS='--appdir=/Applications'
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update > /dev/null
    brew cask install google-chrome
  else
    sudo snap install snapcraft --classic
  fi
cache:
  yarn: true
  directories:
  - node_modules
  - src/node_modules
  - "$(npm config get prefix)/lib/node_modules"
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/docker"
install:
- yarn

before_script:
  - | 
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
    sleep 3 # give xvfb some time to start

  fi

script:
- yarn run build || travis_terminate 1
- yarn run lint || travis_terminate 1
- yarn run test-e2e -- --retries 2 || travis_terminate 1
after_success:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
     yarn run release:linux
  else
     yarn run release:mac
  fi
deploy:
  on:
    branch: master
    condition: $TRAVIS_OS_NAME == "linux"
  provider: script
  script: bash scripts/deploy.sh $GH_TOKEN $TRAVIS_BUILD_NUMBER
  skip_cleanup: true
dd:
  secure: Br5Y8lWXttRgS9MoxmoXJ3BYcc0+lsaHy8sBeoduwtdLIped0OWUq1VWfLO2H11pMCXAFY60Rw1USbm2wGnOp8nx9L1Yo9Nq5sSzaEEujKaS3hetnuGGFsj+2tOuDQ+envWFByzuLfPpAGJNGN3A7k0GYYNUi3kzxJRy1W0d4gfDPpo38X/AVw9kCQS4gXvkk2twWI3fGRlBPnAilzCfTz69aEo850Er/TYvZfMbj9tjJa2HO8l40EXpey7s5ZbrGQJjLM+eCDekmIoDOeWlbzyFj4K3SFhUpAacPvseuF2GCbj4mPPzPlNT0md85JjhNbGQgTmuWHF9iD7ULUDSHwVyFZePW8KDuZzns9oKx5qdbM8ATh8D4b4z03LlE1vPBH3Klij7WfFp0yLZq/PaUWhVvP6Br1KZrMByMrlaEA/Dn8Xw6Sbed8ipG9NZDjPVU4fh2onrEw/He09DWfddoRbYGgkNKKOPbR2mTO5qnFtWz25LX26q/cq2Eh4Twt3imE1EqMdWZ3DbGzoakhTkJCZmGj11TCgBJ5nmV8gJ/FwGjv49zWg2kdM2EgQVpTDvD++wh3LMboBfADoA/tEDF2qZxOF0Looa/Vnph0MU6843YyfY0MAhLDZ/Vj+231De5J413QItVBMw2JPKNnoR6FAmkoO9nuv5EzBf7je3XjE=
