image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm run build
  # run tests
  - npm run test-e2e

deploy_script:
- cmd: npm run release:win

artifacts:
  - path: 'dist\*.exe'
  - path: 'dist\latest.yml'